name: Build and deploy

on:
  schedule:
    # run every 24 hours on the 43rd minute (github actions sees higher usage on
    # the 0th minute)
    - cron: 43 */24 * * *
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: yarn install --frozen-lockfile
      - env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: yarn export
      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --prodIfUnlocked --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=out/
